"""Second Revision

Revision ID: cfb6f6a2d6d7
Revises: 4fe5117bd759
Create Date: 2023-10-07 10:18:11.753136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cfb6f6a2d6d7'
down_revision: Union[str, None] = '4fe5117bd759'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admins')
    op.drop_table('students')
    op.drop_index('ix_check_out_id', table_name='check_out')
    op.drop_table('check_out')
    op.drop_table('teachers')
    op.drop_index('ix_check_in_id', table_name='check_in')
    op.drop_table('check_in')
    op.drop_table('staff')
    op.drop_index('ix_card_pass_index', table_name='card_pass')
    op.drop_table('card_pass')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_pass',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('staff', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('index', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('index', name='card_pass_pkey')
    )
    op.create_index('ix_card_pass_index', 'card_pass', ['index'], unique=False)
    op.create_table('staff',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='staff_pkey')
    )
    op.create_table('check_in',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('checkin_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='check_in_pkey')
    )
    op.create_index('ix_check_in_id', 'check_in', ['id'], unique=False)
    op.create_table('teachers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='teachers_pkey')
    )
    op.create_table('check_out',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('checkout_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='check_out_pkey')
    )
    op.create_index('ix_check_out_id', 'check_out', ['id'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('paid', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='students_pkey')
    )
    op.create_table('admins',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('born', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('gmail', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('region', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_staff', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='admins_pkey')
    )
    # ### end Alembic commands ###
